@base_url = http://localhost:3333

// Root
GET {{base_url}}

###
//Create Products
POST {{base_url}}/products
content-type: application/json

{
  "name": "Moby Dick",
  "price": 2989,
  "quantity": 20
}

###
# @name list_products
// Index Products
GET {{base_url}}/products

###
// Get one product id
@product_id = {{list_products.response.body.$[0].id}}

###
// Show Product
GET {{base_url}}/products/{{product_id}}

###
// Delete Product
DELETE {{base_url}}/products/{{product_id}}
